before_script:
  - mysql -e 'create database activeuuid_test;'
  - psql -c 'create database activeuuid_test;' -U postgres

rvm:
  - 1.9.3
  - 2.0.0
  - rbx-2
  - jruby-1.7.13

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3-1
  - gemfiles/Gemfile.rails-3-2
  - gemfiles/Gemfile.rails-4-0
  - gemfiles/Gemfile.rails-head

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql
  - DB=jdbc-mysql

matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head
